### ISSUE TITLE
Traceback (most recent call last):   File "D:\All_Projecte\DETR_pytorch-main\main.py", line 35, in <module>     wandb.init( AttributeError: module 'wandb' has no attribute 'init'

### ISSUE THREAD

**Issue by ssl0614** [areumsim/DETR_pytorch#1]
我下载了源码，运行main.py文件这个错误，怎么解决？

**Comment by 1dhuh** [comment]
here i got new problem,Traceback (most recent call last):
  File "D:\biyelunwen\DETR_pytorch-main\main.py", line 54, in <module>
    coco_train = COCODataset(
  File "D:\biyelunwen\DETR_pytorch-main\dataloader_v3.py", line 82, in __init__
    self.coco = COCO(self.anno_file)
  File "D:\anaconda\lib\site-packages\pycocotools\coco.py", line 81, in __init__
    with open(annotation_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\wolve\\arsim\\detr_git\\DETR_pytorch\\cocodataset\\annotations\\instances_train2017.json'
